-- Guru Ji internet map schema 004_intelligence_map
-- Generated from app.internet_intelligence.map.store; edit the store, not this file.
CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS intel_entities ( entity_id TEXT PRIMARY KEY, institution_id TEXT NOT NULL, kind TEXT NOT NULL, name TEXT NOT NULL, names_json TEXT NOT NULL DEFAULT '[]', locations_json TEXT NOT NULL DEFAULT '[]', group_label TEXT NOT NULL DEFAULT '', parent_id TEXT, authority TEXT NOT NULL DEFAULT 'self', status TEXT NOT NULL DEFAULT 'active', notes TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(institution_id, kind, name) );
CREATE INDEX IF NOT EXISTS idx_intel_entities_institution ON intel_entities(institution_id, kind);
CREATE TABLE IF NOT EXISTS intel_assets ( asset_id TEXT PRIMARY KEY, institution_id TEXT NOT NULL, entity_id TEXT, asset_key TEXT NOT NULL, platform TEXT NOT NULL, kind TEXT NOT NULL, url TEXT NOT NULL, handle TEXT NOT NULL, relation TEXT NOT NULL DEFAULT 'unknown', grade TEXT NOT NULL DEFAULT 'unrated', grade_reasons_json TEXT NOT NULL DEFAULT '[]', proposed_grade TEXT, scorer_version TEXT, status TEXT NOT NULL DEFAULT 'unknown', platform_id TEXT, followers INTEGER, followers_source TEXT, followers_at TEXT, last_verified_at TEXT, last_verified_via TEXT, note TEXT NOT NULL DEFAULT '', first_seen_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(institution_id, asset_key) );
CREATE INDEX IF NOT EXISTS idx_intel_assets_institution ON intel_assets(institution_id, platform, grade);
CREATE TABLE IF NOT EXISTS intel_evidence ( evidence_id TEXT PRIMARY KEY, institution_id TEXT NOT NULL, asset_id TEXT NOT NULL, kind TEXT NOT NULL, polarity TEXT NOT NULL DEFAULT 'supports', source_url TEXT NOT NULL DEFAULT '', source_asset_id TEXT, detail TEXT NOT NULL DEFAULT '', channel TEXT NOT NULL DEFAULT '', observed_via TEXT NOT NULL DEFAULT 'live', run_id TEXT, raw_sha256 TEXT, observed_at TEXT NOT NULL );
CREATE INDEX IF NOT EXISTS idx_intel_evidence_asset ON intel_evidence(institution_id, asset_id, observed_at);
CREATE INDEX IF NOT EXISTS idx_intel_evidence_source ON intel_evidence(institution_id, source_asset_id, kind);
CREATE TABLE IF NOT EXISTS intel_gold_items ( gold_id TEXT PRIMARY KEY, institution_id TEXT NOT NULL, asset_key TEXT NOT NULL, platform TEXT NOT NULL, entity_name TEXT NOT NULL DEFAULT '', relation TEXT NOT NULL DEFAULT 'unknown', split TEXT NOT NULL, expected_min_grade TEXT NOT NULL DEFAULT 'C', source TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, UNIQUE(institution_id, asset_key) );
CREATE TABLE IF NOT EXISTS intel_suppression ( institution_id TEXT NOT NULL, key_hmac TEXT NOT NULL, reason TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, PRIMARY KEY(institution_id, key_hmac) );
CREATE TABLE IF NOT EXISTS intel_map_runs ( run_id TEXT PRIMARY KEY, institution_id TEXT NOT NULL, kind TEXT NOT NULL DEFAULT 'tick', started_at TEXT NOT NULL, finished_at TEXT, status TEXT NOT NULL, stop_reason TEXT, gate TEXT, spend_json TEXT NOT NULL DEFAULT '{}', counts_json TEXT NOT NULL DEFAULT '{}', metrics_json TEXT NOT NULL DEFAULT '{}', error TEXT );
CREATE INDEX IF NOT EXISTS idx_intel_map_runs_institution ON intel_map_runs(institution_id, started_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_intel_map_runs_one_tick ON intel_map_runs(institution_id, kind) WHERE status = 'running' AND kind = 'tick';
CREATE TABLE IF NOT EXISTS intel_sources ( source_id TEXT PRIMARY KEY, institution_id TEXT NOT NULL, connector TEXT NOT NULL, target TEXT NOT NULL, entity_id TEXT, asset_id TEXT, topic TEXT NOT NULL DEFAULT '', origin TEXT NOT NULL DEFAULT 'seed', work_class TEXT NOT NULL DEFAULT 'rotation', hops INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'active', due_at TEXT NOT NULL, interval_seconds INTEGER NOT NULL DEFAULT 86400, lease_owner TEXT, lease_until TEXT, etag TEXT, last_modified TEXT, last_outcome TEXT, failure_streak INTEGER NOT NULL DEFAULT 0, runs INTEGER NOT NULL DEFAULT 0, yield_total INTEGER NOT NULL DEFAULT 0, yield_last INTEGER NOT NULL DEFAULT 0, cost_total REAL NOT NULL DEFAULT 0, expires_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(institution_id, connector, target) );
CREATE INDEX IF NOT EXISTS idx_intel_sources_due ON intel_sources(institution_id, status, due_at);
CREATE TABLE IF NOT EXISTS intel_quota ( institution_id TEXT NOT NULL, day TEXT NOT NULL, connector TEXT NOT NULL, units REAL NOT NULL DEFAULT 0, calls INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(institution_id, day, connector) );
CREATE TABLE IF NOT EXISTS intel_review_items ( review_id TEXT PRIMARY KEY, institution_id TEXT NOT NULL, kind TEXT NOT NULL, fingerprint TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', severity TEXT NOT NULL DEFAULT 'normal', asset_id TEXT, entity_id TEXT, title TEXT NOT NULL, detail TEXT NOT NULL DEFAULT '', url TEXT NOT NULL DEFAULT '', connector TEXT NOT NULL DEFAULT '', source_id TEXT, run_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, expires_at TEXT, decision TEXT, decision_note TEXT, decided_by TEXT, decided_at TEXT, UNIQUE(institution_id, fingerprint) );
CREATE INDEX IF NOT EXISTS idx_intel_review_items_open ON intel_review_items(institution_id, status, created_at);
CREATE TABLE IF NOT EXISTS intel_incidents ( incident_id TEXT PRIMARY KEY, institution_id TEXT NOT NULL, kind TEXT NOT NULL, target TEXT NOT NULL, fingerprint TEXT NOT NULL, severity TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', title TEXT NOT NULL, signals_json TEXT NOT NULL DEFAULT '[]', examples_json TEXT NOT NULL DEFAULT '[]', guidance TEXT NOT NULL DEFAULT '', connector TEXT NOT NULL DEFAULT '', run_id TEXT, first_seen_at TEXT NOT NULL, last_seen_at TEXT NOT NULL, times_seen INTEGER NOT NULL DEFAULT 1, notified_at TEXT, acknowledged_by TEXT, acknowledged_at TEXT, resolved_by TEXT, resolved_at TEXT, note TEXT NOT NULL DEFAULT '', UNIQUE(institution_id, fingerprint) );
CREATE INDEX IF NOT EXISTS idx_intel_incidents_open ON intel_incidents(institution_id, status, severity);
CREATE TABLE IF NOT EXISTS intel_fetch_validators ( institution_id TEXT NOT NULL, url_sha256 TEXT NOT NULL, etag TEXT, last_modified TEXT, outcome TEXT NOT NULL, content_sha256 TEXT, fetched_at TEXT NOT NULL, PRIMARY KEY(institution_id, url_sha256) );
CREATE TABLE IF NOT EXISTS intel_budget_ledger ( day TEXT NOT NULL, connector TEXT NOT NULL, units REAL NOT NULL DEFAULT 0, calls INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(day, connector) );
ALTER TABLE intel_assets ADD COLUMN IF NOT EXISTS last_activity_at TEXT;
ALTER TABLE intel_assets ADD COLUMN IF NOT EXISTS registration_expires_at TEXT;
ALTER TABLE intel_sources ADD COLUMN IF NOT EXISTS priority REAL NOT NULL DEFAULT 0;
ALTER TABLE intel_sources ADD COLUMN IF NOT EXISTS base_interval_seconds INTEGER;
ALTER TABLE intel_assets ADD COLUMN IF NOT EXISTS proposed_reasons_json TEXT;
ALTER TABLE intel_assets ADD COLUMN IF NOT EXISTS proposed_scorer TEXT;
ALTER TABLE intel_assets ADD COLUMN IF NOT EXISTS proposed_run_id TEXT;
-- PostgreSQL row-level security (skipped on SQLite)
ALTER TABLE intel_entities ENABLE ROW LEVEL SECURITY;
ALTER TABLE intel_entities FORCE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = current_schema() AND tablename = 'intel_entities' AND policyname = 'intel_entities_tenant_isolation') THEN CREATE POLICY intel_entities_tenant_isolation ON intel_entities USING (institution_id = current_setting('app.institution_id', true)) WITH CHECK (institution_id = current_setting('app.institution_id', true)); END IF; END $$;
ALTER TABLE intel_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE intel_assets FORCE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = current_schema() AND tablename = 'intel_assets' AND policyname = 'intel_assets_tenant_isolation') THEN CREATE POLICY intel_assets_tenant_isolation ON intel_assets USING (institution_id = current_setting('app.institution_id', true)) WITH CHECK (institution_id = current_setting('app.institution_id', true)); END IF; END $$;
ALTER TABLE intel_evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE intel_evidence FORCE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = current_schema() AND tablename = 'intel_evidence' AND policyname = 'intel_evidence_tenant_isolation') THEN CREATE POLICY intel_evidence_tenant_isolation ON intel_evidence USING (institution_id = current_setting('app.institution_id', true)) WITH CHECK (institution_id = current_setting('app.institution_id', true)); END IF; END $$;
ALTER TABLE intel_gold_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE intel_gold_items FORCE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = current_schema() AND tablename = 'intel_gold_items' AND policyname = 'intel_gold_items_tenant_isolation') THEN CREATE POLICY intel_gold_items_tenant_isolation ON intel_gold_items USING (institution_id = current_setting('app.institution_id', true)) WITH CHECK (institution_id = current_setting('app.institution_id', true)); END IF; END $$;
ALTER TABLE intel_suppression ENABLE ROW LEVEL SECURITY;
ALTER TABLE intel_suppression FORCE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = current_schema() AND tablename = 'intel_suppression' AND policyname = 'intel_suppression_tenant_isolation') THEN CREATE POLICY intel_suppression_tenant_isolation ON intel_suppression USING (institution_id = current_setting('app.institution_id', true)) WITH CHECK (institution_id = current_setting('app.institution_id', true)); END IF; END $$;
ALTER TABLE intel_map_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE intel_map_runs FORCE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = current_schema() AND tablename = 'intel_map_runs' AND policyname = 'intel_map_runs_tenant_isolation') THEN CREATE POLICY intel_map_runs_tenant_isolation ON intel_map_runs USING (institution_id = current_setting('app.institution_id', true)) WITH CHECK (institution_id = current_setting('app.institution_id', true)); END IF; END $$;
ALTER TABLE intel_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE intel_sources FORCE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = current_schema() AND tablename = 'intel_sources' AND policyname = 'intel_sources_tenant_isolation') THEN CREATE POLICY intel_sources_tenant_isolation ON intel_sources USING (institution_id = current_setting('app.institution_id', true)) WITH CHECK (institution_id = current_setting('app.institution_id', true)); END IF; END $$;
ALTER TABLE intel_quota ENABLE ROW LEVEL SECURITY;
ALTER TABLE intel_quota FORCE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = current_schema() AND tablename = 'intel_quota' AND policyname = 'intel_quota_tenant_isolation') THEN CREATE POLICY intel_quota_tenant_isolation ON intel_quota USING (institution_id = current_setting('app.institution_id', true)) WITH CHECK (institution_id = current_setting('app.institution_id', true)); END IF; END $$;
ALTER TABLE intel_review_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE intel_review_items FORCE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = current_schema() AND tablename = 'intel_review_items' AND policyname = 'intel_review_items_tenant_isolation') THEN CREATE POLICY intel_review_items_tenant_isolation ON intel_review_items USING (institution_id = current_setting('app.institution_id', true)) WITH CHECK (institution_id = current_setting('app.institution_id', true)); END IF; END $$;
ALTER TABLE intel_incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE intel_incidents FORCE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = current_schema() AND tablename = 'intel_incidents' AND policyname = 'intel_incidents_tenant_isolation') THEN CREATE POLICY intel_incidents_tenant_isolation ON intel_incidents USING (institution_id = current_setting('app.institution_id', true)) WITH CHECK (institution_id = current_setting('app.institution_id', true)); END IF; END $$;
ALTER TABLE intel_fetch_validators ENABLE ROW LEVEL SECURITY;
ALTER TABLE intel_fetch_validators FORCE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = current_schema() AND tablename = 'intel_fetch_validators' AND policyname = 'intel_fetch_validators_tenant_isolation') THEN CREATE POLICY intel_fetch_validators_tenant_isolation ON intel_fetch_validators USING (institution_id = current_setting('app.institution_id', true)) WITH CHECK (institution_id = current_setting('app.institution_id', true)); END IF; END $$;
